FROM nginx:1.21-alpine
# #Remove the location of the nginx configuration
# RUN  rm /etc/nginx/conf.d/default.conf
# # #Copy from our project configuration to the container created directory
# COPY conf.d/ /etc/nginx/conf.d


