# Generated by Django 4.0 on 2024-03-30 18:50

from django.db import migrations, models
import django.db.models.deletion
import test_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('release_year', models.DateField()),
                ('cover_image', models.ImageField(null=True, upload_to=test_api.models.Album.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Artise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to=test_api.models.Artise.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(null=True, upload_to=test_api.models.Track.upload_to)),
                ('name', models.TextField()),
                ('track_url', models.URLField()),
                ('year_release', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_api.album')),
                ('artise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_artise', to='test_api.artise')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_genre', to='test_api.genre')),
            ],
        ),
        migrations.AddField(
            model_name='artise',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='artise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.artise'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.genre'),
        ),
    ]
