name: Check

on: 
  push:
    branches:
      - main

jobs:
  test_link:
    name: Test and Link
    runs-on: ubuntu-20.04

    env:
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 #action has a run embeded in it
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name : Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

        # - name : Test
        #   run: sh -c "pip install requirements.txt && python manage.py test"

        #u can add a job to test and then deploy to dockerhub or aws ec2 instance



